Repository Dae-Hwa/baseball, pull requests merged in 2021-05, with the labels that each got.

#22 [FE] 글로벌 백그라운드 이미지 삽입 및 포지셔닝
  FE/package-lock.json
  FE/package.json
  FE/public/image/mlbground_edit.jpg
  FE/src/App.css
  FE/src/App.js
  FE/src/GlobalStyle.jsx
  FE/src/components/Home/Home.jsx
  FE/src/components/InGame/InGame.jsx
  FE/src/index.css
  FE/src/index.js
  FE/src/logo.svg
Labels: FE, Goody, style

#24 [FE] Intro 컴포넌트 완료
  FE/package.json
  FE/src/components/Intro/Game.jsx
  FE/src/components/Intro/Intro.jsx
  FE/src/components/Intro/TeamSelect.jsx
Labels: FE

#27 [FE] : Pitch 결과 산출 함수 추가
  .github/workflows/test-api-server.yml
  FE/package.json
  FE/src/App.js
  FE/src/utils/getRandomPitchResult/getRandomPitchResult.js
  FE/src/utils/getRandomPitchResult/test.js
Labels: FE, Goody, enhancement

#30 [FE] 가운데 정렬 및 ScoreBoard 컴포넌트 일부 구현
  FE/package-lock.json
  FE/src/App.js
  FE/src/GlobalStyle.jsx
  FE/src/components/InGame/InGame.jsx
  FE/src/components/InGame/ScoreBoard/ScoreBoard.jsx
  FE/src/components/InGame/ScoreBoard/Table.jsx
  FE/src/components/Intro/Intro.jsx
  FE/src/components/Intro/TeamSelect.jsx
Labels: FE

#38 [FE] OAuth 추가
  FE/package-lock.json
  FE/package.json
  FE/src/components/Home/Home.jsx
  FE/src/config/authMethods.js
  FE/src/config/firebase-config.js
  FE/src/service/auth.js
Labels: FE, Goody, feature

#39 [FE] Ground 컴포넌트 구현
  FE/public/image/base.png
  FE/public/image/base2.png
  FE/public/image/batter.png
  FE/public/image/pitcher.png
  FE/public/image/pitcher_eagles.png
  FE/public/image/pitcher_eagles_heart.png
  FE/public/image/runner_running.png
  FE/public/image/runner_waiting.png
  FE/src/components/InGame/Ground/BallCount.jsx
  FE/src/components/InGame/Ground/Ground.jsx
  FE/src/components/InGame/Ground/Header.jsx
  FE/src/components/InGame/Ground/Main.jsx
  FE/src/components/InGame/InGame.jsx
  FE/src/components/InGame/LineUp/Table.jsx
  FE/src/components/InGame/ScoreBoard/Table.jsx
  FE/src/components/Intro/TeamSelect.jsx
Labels: FE

#43 [FE] 인게임화면 레코드 스켈레톤 스타일링
  FE/src/components/InGame/InGame.jsx
  FE/src/components/InGame/Record/Bottom.jsx
  FE/src/components/InGame/Record/Record.jsx
  FE/src/components/InGame/Record/RecordOfPlayer.jsx
  FE/src/components/InGame/Record/Top.jsx
Labels: FE, Goody, style

#46 [FE] upstream PR/merge 후 rebase 대체
  .github/workflows/test-api-server.yml
  .gitignore
  BE/init
  FE/.gitignore
  FE/README.md
  FE/package-lock.json
  FE/package.json
  FE/public/favicon.ico
  FE/public/image/base.png
  FE/public/image/base2.png
  FE/public/image/batter.png
  FE/public/image/mlbground_edit.jpg
  FE/public/image/pitcher.png
  FE/public/image/pitcher_eagles.png
  FE/public/image/pitcher_eagles_heart.png
  FE/public/image/runner_running.png
  FE/public/image/runner_waiting.png
  FE/public/index.html
  FE/public/logo192.png
  FE/public/logo512.png
  FE/public/manifest.json
  FE/public/robots.txt
  FE/src/App.js
  FE/src/App.test.js
  FE/src/GlobalStyle.jsx
  FE/src/components/Home/Home.jsx
  FE/src/components/InGame/Ground/BallCount.jsx
  FE/src/components/InGame/Ground/Ground.jsx
  FE/src/components/InGame/Ground/Header.jsx
  FE/src/components/InGame/Ground/Main.jsx
  FE/src/components/InGame/InGame.jsx
  FE/src/components/InGame/LineUp/LineUp.jsx
  FE/src/components/InGame/LineUp/Table.jsx
  FE/src/components/InGame/Record/Bottom.jsx
  FE/src/components/InGame/Record/Record.jsx
  FE/src/components/InGame/Record/RecordOfPlayer.jsx
  FE/src/components/InGame/Record/Top.jsx
  FE/src/components/InGame/ScoreBoard/ScoreBoard.jsx
  FE/src/components/InGame/ScoreBoard/Table.jsx
  FE/src/components/Intro/Game.jsx
  FE/src/components/Intro/Intro.jsx
  FE/src/components/Intro/TeamSelect.jsx
  FE/src/components/NoMatch/NoMatch.jsx
  FE/src/config/authMethods.js
  FE/src/config/firebase-config.js
  FE/src/env.css
  FE/src/index.js
  FE/src/reportWebVitals.js
  FE/src/service/auth.js
  FE/src/setupTests.js
  FE/src/utils/getRandomPitchResult/getRandomPitchResult.js
  FE/src/utils/getRandomPitchResult/test.js
Labels: Common

#48 [FE] Ground 진루 애니메이션
  FE/src/components/InGame/Ground/Field.jsx
  FE/src/components/InGame/Ground/Ground.jsx
  FE/src/components/InGame/Ground/Main.jsx
  FE/src/components/InGame/Ground/Score.jsx
Labels: FE

#50 [FE] Pitcher Animation
  FE/public/image/pitcher_release.png
  FE/public/image/pitcher_throwing.png
  FE/public/image/pitcher_windup.png
  FE/src/components/InGame/Ground/Field.jsx
Labels: FE

#54 [FE] 홈화면 로그인 기능 및 스타일링
  .gitignore
  FE/init
  FE/public/image/Github-Logo.png
  FE/public/image/Google-Logo.png
  FE/public/image/pitcher.png
  FE/src/components/Home/Home.jsx
  FE/src/components/InGame/Ground/Ground.jsx
  FE/src/components/InGame/Ground/Header.jsx
  FE/src/components/InGame/Ground/Main.jsx
  FE/src/config/authProvider.js
Labels: FE, Goody, enhancement, style

#58 [FE] ScoreBoard / LineUp fetch
  FE/src/components/InGame/InGame.jsx
  FE/src/components/InGame/LineUp/LineUp.jsx
  FE/src/components/InGame/LineUp/Table.jsx
  FE/src/components/InGame/ScoreBoard/ScoreBoard.jsx
  FE/src/components/InGame/ScoreBoard/Table.jsx
  FE/src/utils/makeDecimalPoint/makeDecimalPoint.js
Labels: FE

#63 [FE] useContext 적용
  FE/public/image/pitcher_windup.png
  FE/src/App.js
  FE/src/components/InGame/Ground/Field.jsx
  FE/src/components/InGame/InGame.jsx
  FE/src/components/Intro/Game.jsx
  FE/src/components/Intro/TeamSelect.jsx
  FE/src/components/Main.jsx
Labels: FE

#67 Be/feature/mockup
  BE/baseball-be/build.gradle
  BE/baseball-be/src/main/java/kr/codesquad/baseball/game/GameController.java
  BE/baseball-be/src/main/java/kr/codesquad/baseball/game/GameDTO.java
  BE/baseball-be/src/main/java/kr/codesquad/baseball/game/GameScoresDTO.java
  BE/baseball-be/src/main/java/kr/codesquad/baseball/game/LineUpDTO.java
  BE/baseball-be/src/main/java/kr/codesquad/baseball/game/PlayerStatus.java
  BE/baseball-be/src/main/java/kr/codesquad/baseball/inning/BaseState.java
  BE/baseball-be/src/main/java/kr/codesquad/baseball/inning/HitterRecord.java
  BE/baseball-be/src/main/java/kr/codesquad/baseball/inning/InningController.java
  BE/baseball-be/src/main/java/kr/codesquad/baseball/inning/InningDTO.java
  BE/baseball-be/src/main/java/kr/codesquad/baseball/player/PlayerDTO.java
  BE/baseball-be/src/main/java/kr/codesquad/baseball/team/TeamDTO.java
  BE/baseball-be/src/main/java/kr/codesquad/baseball/utils/SampleDataFactory.java
Labels: BE

#77 [FE] 레코드 진행중만 뜨는 버그 수정
  FE/src/components/InGame/Ground/Field.jsx
  FE/src/components/InGame/Record/RecordOfPlayer.jsx
Labels: FE, Goody, bug
